name:                Risk-Game
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- MonadRandom
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  Risk-Game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Risk-Game

tests:
  Risk-Game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Risk-Game
